### PR TITLE
nrfx-blink-sdk: Fix incompatible PIC setting and libc usage

### PR DESCRIPTION
**Pull request by kubamracek**
The changes here are a bit subtle (I with the build system and tools from the Zephyr SDK were more strict and more verbose, but it is what it is):

- Object files are expected to have PIC off, all C and C++ compilations already have it, so we need to match that on Swift compilations. This fixes the mysterious linker error described in https://github.com/apple/swift-embedded-examples/issues/38.

- We should explicitly build with -Osize, as CMake's default is to not pass any -Onone/-O/-Osize flags when the user has not explicitly provided a CMAKE_BUILD_TYPE. (C/C++ compilations are defaulted to -Os in the Zephyr CMake setup already.)

- Disable the stack protectors (they require more symbols provided from a libc but they are not available in the Zephyr SDK).

- Explicitly ask for newlib as the selected libc (to avoid symbol clashes with picolibc) in prj.conf. This makes malloc/free and aligned_alloc available.

- Implement posix_memalign on top of aligned_alloc. This satisfies the requirements on heap API from Embedded Swift.

Fixes https://github.com/apple/swift-embedded-examples/issues/38.

### CODE REVIEW

**Comment by kubamracek** [comment]
Didn't test this yet on a nRF board, will do that before merging. But @nrbrook if you'd like to give it a try, feel free to!

**Comment by nrbrook** [comment]
Thanks @kubamracek. When building I'm getting `'newlib.h' file not found`.  If I add the following it gets past that, but then `picolibc.h` can't be found, which doesn't seem to be present in zephyr. I'm not sure what's going wrong here and can't see much from searching around...
```
target_include_directories(app PRIVATE
    ${ZEPHYR_BASE}/../modules/lib/picolibc/newlib/libc/include
)
```

**Comment by kubamracek** [comment]
What version of Zephyr and/or NRF SDK are you using?

**Comment by nrbrook** [comment]
Zephyr, the latest commit in `main`:
```
zephyr % git log --abbrev-commit --pretty=oneline -2
2de6274119c (HEAD -> main, origin/main, origin/HEAD) drivers: flash: Do not select NRFX_RRAMC while building with TF-M
```

**Comment by kubamracek** [comment]
Could you post the entire build error complaining about newlib.h?

**Comment by kubamracek** [comment]
Btw I finally got to upload the firmware from this PR to a nRF52840-DK and it works (for me).

**Comment by kubamracek** [comment]
I have wiped my Zephyr installation and re-installed it to get the latest development version (this commit: https://github.com/zephyrproject-rtos/zephyr/commit/2aa31a369514a8ecb32dc5287eb446e117c28ade), and I don't reproduce the problem, the setup from this PR builds fine:

```
(.venv) cmake --build build
[1/134] Preparing syscall dependency handling

[3/134] Generating include/generated/zephyr/version.h
-- Zephyr version: 3.7.99 (/Users/kuba/zephyrproject/zephyr), build: v3.7.0-775-g2aa31a369514
[127/134] Linking Swift static library app/libapp.a
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive library: /Users/kuba/Documents/swift-embedded-examples/nrfx-blink-sdk/build/app/libapp.a the table of contents is empty (no object file members in the library define global symbols)
[129/134] Linking C executable zephyr/zephyr_pre0.elf
/Users/kuba/zephyr-sdk-0.16.8/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: warning: orphan section `.swift_modhash' from `app/libapp.a(Main.swift.obj)' being placed in section `.swift_modhash'
[134/134] Linking C executable zephyr/zephyr.elf
/Users/kuba/zephyr-sdk-0.16.8/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: warning: orphan section `.swift_modhash' from `app/libapp.a(Main.swift.obj)' being placed in section `.swift_modhash'
Memory region         Used Size  Region Size  %age Used
           FLASH:       20896 B         1 MB      1.99%
             RAM:        5696 B       256 KB      2.17%
        IDT_LIST:          0 GB        32 KB      0.00%
Generating files from /Users/kuba/Documents/swift-embedded-examples/nrfx-blink-sdk/build/zephyr/zephyr.elf for board: nrf52840dk
```

I wonder if you possibly just have some specific commit of Zephyr where the picolibc support is busted?

**Comment by kubamracek** [comment]
Let's go ahead and merge this, and if there's any remaining issues, let's take that separately.

**Pull request merged**
