### PR TITLE
Update nrfx-blink-sdk example to use native CMake Swift support

### PR DESCRIPTION
**Pull request by kubamracek**
This should also resolve https://github.com/apple/swift-embedded-examples/issues/14

### CODE REVIEW

**Comment by rauhul** [comment]
@naknut would you be able to verify that this change fixes the crash?

**Comment by bobbelkl** [comment]
For me the `add_library(app_swift OBJECT Main.swift)` solved the issue.
The LED is blinking now.

**Review by rauhul — APPROVED** [review]

**Comment by naknut** [comment]
> @naknut would you be able to verify that this change fixes the crash?

I'm on vacation at the moment @rauhul . Will try to verify later this week or next week.

**Comment by naknut** [comment]
@rauhul I know this is already merged but I wanted to let you know this works on my board now. Thanks @kubamracek for fixing this!

**Pull request merged**
